Mutation:
  type: object
  config:
    name: Mutation
    fields:
      loginUser:
        description: 'Log the user'
        access: "@=isAnonymous()"
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: LoginUserInput
          payloadType: LoginUserPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\User\\LoginUserMutation", [value])'
      registerUser:
        description: 'I am the registerUser description'
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: RegisterUserInput
          payloadType: RegisterUserPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\RegisterUserMutation", [value])'
