Query:
  type: object
  config:
    fields:
      viewer:
        access: '@=isAuthenticated()'
        type: User!
        description: The currently authenticated user.
        resolve: '@=getUser()'
      node:
        builder: "Relay::Node"
        builderConfig:
          nodeInterfaceType: Node
          idFetcher: '@=resolver("App\\GraphQL\\Resolver\\GlobalIdResolver", [value])'