Query:
  type: object
  config:
    fields:
      viewer:
        access: '@=isAuthenticated()'
        type: User!
        description: The currently authenticated user.
        resolve: '@=getUser()'
      node:
        builder: "Relay::Node"
        builderConfig:
          nodeInterfaceType: Node
          idFetcher: '@=resolver("App\\GraphQL\\Resolver\\GlobalIdResolver", [value])'
      viewerTeams:
        description: 'Get the list of viewer teams'
        type: '[Team]'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\ViewerTeamsResolver", [args, getUser()])'
      teamBoards:
        description: 'Get the list of boards belonging to a team'
        type: '[Board]'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\TeamBoardsResolver", [args, getUser()])'
        args:
          teamId:
            type: ID!